# Generated by Django 4.2.10 on 2026-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('MA', 'Math/Numpy')], max_length=2)),
                ('body', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
